#!/bin/sh
export gamemedia="/exposed/DCIM/Game media/sky"
if [ -d "${gamemedia}" ]; then
mkdir "${gamemedia}/Processed"
cd "${gamemedia}"
#ffmpeg routines
while true ; do
for a in $(ls .); do
if [ ! -f "${gamemedia}/Processed/${a}_Processed.mp4" ]; then
#echo "${a}" > "${gamemedia}/Processed/${a}_Processed"
#https://superuser.com/questions/1005315/interpolation-with-ffmpeg
echo ${a} Processing Debug
#https://superuser.com/questions/1222592/ffmpeg-fps-interpolation-error
#Smartblur https://forum.videohelp.com/threads/389480-Need-help-with-FFMpeg-and-detail-enhancement-sharpening

ffmpeg -i "${a}" -qscale:v 3 -filter:v "minterpolate='fps=60', spp=5:10:0:1, smartblur=1.5:-0.35:-3.5:0.65:0.25:2.0" -c:a copy "Processed/${a}_Processed.mp4"
fi
done
sleep 30
done
else
echo SKY folder not detected!
echo did you grant me the storage access
exit
fi
