#!/bin/sh
export gamemedia="/exposed/DCIM/Game media/sky"
if [ -d "${gamemedia}" ]; then
mkdir "${gamemedia}/Processed"
cd "${gamemedia}"
#ffmpeg routines
while true ; do
for a in $(ls .); do
if [ ! -f "${gamemedia}/Processed/${a}_Processed.mp4" ]; then
#echo "${a}" > "${gamemedia}/Processed/${a}_Processed"
#https://superuser.com/questions/1005315/interpolation-with-ffmpeg
echo ${a} Processing Debug
#https://superuser.com/questions/1222592/ffmpeg-fps-interpolation-error
ffmpeg -i "${a}" -filter "minterpolate='fps=60'" -c:a copy  "Processed/${a}_Processed.mp4"
fi
done
sleep 30
done
else
echo SKY folder not detected!
echo did you grant me the storage access
exit
fi
