#!/bin/bash
set -x
export gamemedia="/exposed/DCIM/Game media/sky"
if [ -d "${gamemedia}" ]; then
mkdir "${gamemedia}/Processed"
rm -rfv "${gamemedia}/temp"
mkdir "${gamemedia}/temp"
cd "${gamemedia}"
#ffmpeg routines
while true ; do
cd "${gamemedia}"
for a in $(ls .); do
export vidtarget=${a}
if [ ! -f "${gamemedia}/Processed/${a}_Processed.mp4" ] && [ ${a} != "Processed" ] && [ ${a} != "temp" ]; then
echo ${a} Converting video into 62fps

ffmpeg -i "${a}" -qscale:v 3 -filter:v "minterpolate='fps=62', spp=5:10:0:1, smartblur=1.5:-0.35:-3.5:0.65:0.25:2.0" -c:a copy "Processed/${a}_Processed.mp4"
## Concatenate to Processed folder
fi
done
sleep 30
done
else
echo SKY folder not detected!
echo did you grant me the storage access
exit
fi
